### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by TheTrueInfinity** [Pointifix/HistoryPlugin#3]
Hello, can you help me? Here is the error:
![err1](https://user-images.githubusercontent.com/112196968/190210276-698ca69d-bbfe-4d44-9388-bd7c70a853f7.png)

**Comment by Pointifix** [comment]
Hello, i just updated the plugin for the mindustry version v126.2

Download the latest release now and it should work (if you are using any of the new erikir alpha releases it might/will not work)
